insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (1, 'Tehachapi Linanthus', 82, 14, 32.39, 9);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (2, 'Pitchersage', 93, 23, 43.65, 8);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (3, 'Bitter Rubberweed', 83, 65, 66.92, 6);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (4, 'Hollyleaf Clover', 96, 32, 96.93, 9);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (5, 'Broom Crowberry', 99, 55, 48.88, 11);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (6, 'Areca Palm', 85, 11, 48.89, 7);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (7, 'Hapeman''s Coolwort', 100, 50, 23.24, 6);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (8, 'Beach Seepweed', 87, 6, 37.64, 12);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (9, 'Rockdaisy', 98, 38, 50.12, 5);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (10, 'Goldenstar', 89, 44, 82.73, 8);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (11, 'Acute Spikerush', 81, 68, 93.54, 9);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (12, 'Rose Mock Vervain', 93, 27, 69.08, 10);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (13, 'Balbis'' Milkvine', 80, 8, 39.4, 9);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (14, 'Yellow Rabbitbrush', 82, 51, 73.26, 6);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (15, 'Parry''s Milkvetch', 80, 68, 78.3, 1);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (16, 'Hyssopleaf Hedgenettle', 87, 67, 46.74, 1);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (17, 'Cafe Falso', 97, 18, 82.92, 9);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (18, 'Whited''s Milkvetch', 95, 13, 13.35, 1);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (19, 'Glory Of Texas', 84, 59, 33.77, 11);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (20, 'Dicranodontium Moss', 81, 64, 81.69, 12);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (21, 'Woodfern', 90, 7, 29.02, 5);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (22, 'Rosewood', 88, 15, 96.6, 10);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (23, 'Phaeographina Lichen', 90, 49, 18.96, 3);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (24, 'Sierra Pea', 81, 32, 21.56, 1);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (25, 'Twoflower Cinquefoil', 93, 35, 23.79, 5);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (26, 'Lanceleaf Wakerobin', 96, 41, 21.17, 1);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (27, 'Swartz''s Jamaican Broom', 91, 67, 17.58, 2);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (28, 'Cardinal Climber', 96, 18, 55.63, 2);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (29, 'Island Bush Monkeyflower', 90, 11, 21.2, 12);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (30, 'Egger''s Morning-glory', 99, 10, 6.12, 2);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (31, 'Obscure Map Lichen', 99, 66, 30.17, 2);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (32, 'Whitehair Leather Flower', 99, 47, 8.16, 7);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (33, 'Pringle''s Phacelia', 81, 18, 29.97, 12);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (34, 'Hybrid Oak', 86, 30, 1.24, 2);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (35, 'Cutleaf Monkeyflower', 86, 51, 45.36, 8);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (36, 'Hickman''s Popcornflower', 86, 55, 86.62, 3);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (37, 'Nuttall''s Toothwort', 81, 68, 41.15, 10);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (38, 'Spiny Amaranth', 97, 29, 69.76, 2);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (39, 'Orchis', 85, 70, 13.88, 11);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (40, 'Mangrovevine', 99, 35, 67.37, 6);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (41, 'Kaibab Suncup', 94, 51, 83.21, 10);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (42, 'Manyawn Pricklyleaf', 97, 25, 74.78, 7);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (43, 'Ailanthus', 99, 36, 77.91, 6);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (44, 'Alfalfa Dodder', 91, 64, 81.7, 8);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (45, 'Jaffueliobryum Moss', 80, 15, 91.14, 4);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (46, 'Hybrid Oak', 97, 9, 54.36, 5);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (47, 'Scouler''s Fumewort', 89, 12, 57.07, 1);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (48, 'Pitted Stripeseed', 80, 62, 70.38, 8);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (49, 'Oriental Asperula', 93, 11, 90.7, 1);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (50, 'Acuminate Brachythecium Moss', 96, 58, 6.66, 3);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (51, 'Spinystar', 81, 70, 60.43, 2);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (52, 'Walter''s Sedge', 85, 43, 7.0, 12);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (53, 'Divergent Buckwheat', 86, 62, 26.57, 11);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (54, 'Singlenerve Peperomia', 83, 57, 2.45, 6);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (55, 'Redberry Buckthorn', 81, 5, 38.21, 1);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (56, 'Hoary Skullcap', 82, 28, 3.46, 11);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (57, 'Shortawn Foxtail', 87, 10, 57.69, 9);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (58, 'Angel''s-wings', 92, 64, 26.54, 9);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (59, 'John Crownose', 87, 68, 23.76, 9);
insert into "Vegetable" (id, name, "inQuantity", "saleQuantity", price, "gardenId") values (60, 'Bog Bulrush', 86, 36, 12.67, 12);

ALTER SEQUENCE "Vegetable_id_seq" RESTART WITH 61;