insert into "Garden" (id, name, "userId") values (1, 'BANK OF AMERICA', 2);
insert into "Garden" (id, name, "userId") values (2, 'Bank Spółdzielczy w Mszczonowie', 2);
insert into "Garden" (id, name, "userId") values (3, 'FIRST NATIONAL BANK', 2);
insert into "Garden" (id, name, "userId") values (4, 'VR-Bank Memmingen eG', 2);
insert into "Garden" (id, name, "userId") values (5, 'UNION BANK & TRUST', 2);
insert into "Garden" (id, name, "userId") values (6, 'AMERIS BANK', 2);
insert into "Garden" (id, name, "userId") values (7, 'Raiffeisenbank Schaafheim eG', 2);
insert into "Garden" (id, name, "userId") values (8, 'VR Bank Neuburg-Rain eG', 2);
insert into "Garden" (id, name, "userId") values (9, 'PEOPLES BANK', 2);
insert into "Garden" (id, name, "userId") values (10, 'Raiffeisenbank Hiltenfingen eG', 2);
insert into "Garden" (id, name, "userId") values (11, 'BANCO BPM SOCIETA'' PER AZIONI', 2);
insert into "Garden" (id, name, "userId") values (12, 'LA CASSA RURALE - CREDITO COOPERATIVO ADAMELLO GIUDICARIE VALSABBIA PAGANELLA  - SOCIETA'' COOPERATIVA', 2);
insert into "Garden" (id, name, "userId") values (13, 'Volksbank Rheinböllen eG', 2);
insert into "Garden" (id, name, "userId") values (14, 'Raiffeisenbank Dietersheim und Umgebung eG', 2);
insert into "Garden" (id, name, "userId") values (15, 'FIRST STATE BANK', 2);
insert into "Garden" (id, name, "userId") values (16, 'Mega international commercial bank Co, Ltd', 2);
insert into "Garden" (id, name, "userId") values (17, 'Raiffeisenbank Mondseeland eGen', 2);
insert into "Garden" (id, name, "userId") values (18, 'SKJERN BANK A/S', 2);
insert into "Garden" (id, name, "userId") values (19, 'BANCO BPM SOCIETA'' PER AZIONI', 2);
insert into "Garden" (id, name, "userId") values (20, 'BMO HARRIS BANK', 2);
insert into "Garden" (id, name, "userId") values (21, 'UNITED COMMUNITY BANK', 2);
insert into "Garden" (id, name, "userId") values (22, 'ABN AMRO Bank N.V.', 2);
insert into "Garden" (id, name, "userId") values (23, 'Raiffeisenkasse Orth a.d. Donau eGen', 2);
insert into "Garden" (id, name, "userId") values (24, 'FIRST BANK', 2);
insert into "Garden" (id, name, "userId") values (25, 'SAXO BANK A/S', 2);
insert into "Garden" (id, name, "userId") values (26, 'FIRST STATE BANK', 2);
insert into "Garden" (id, name, "userId") values (27, 'BANK OF AMERICA', 2);
insert into "Garden" (id, name, "userId") values (28, 'Sparkasse Emden', 2);
insert into "Garden" (id, name, "userId") values (29, 'Volksbank Riesa eG', 2);
insert into "Garden" (id, name, "userId") values (30, 'PACIFIC WESTERN BANK', 2);
insert into "Garden" (id, name, "userId") values (31, 'UNITED BANK', 2);
insert into "Garden" (id, name, "userId") values (32, 'BANCA DI CREDITO COOPERATIVO DI PONTASSIEVE - SOCIETA'' COOPERATIVA', 2);
insert into "Garden" (id, name, "userId") values (33, 'BANK OF AMERICA', 2);
insert into "Garden" (id, name, "userId") values (34, 'FIRST SECURITY BANK', 2);
insert into "Garden" (id, name, "userId") values (35, 'CAPITAL CITY BANK', 2);
insert into "Garden" (id, name, "userId") values (36, '''BANCA CENTRO EMILIA - CREDITO COOPERATIVO'' SOCIETA'' COOPERATIVA', 2);
insert into "Garden" (id, name, "userId") values (37, 'WESBANCO BANK INC', 2);
insert into "Garden" (id, name, "userId") values (38, 'BANCO BPM SOCIETA'' PER AZIONI', 2);
insert into "Garden" (id, name, "userId") values (39, 'ILLIMITY BANK S.P.A.', 2);
insert into "Garden" (id, name, "userId") values (40, 'Kreissparkasse Rottweil', 2);
insert into "Garden" (id, name, "userId") values (41, 'HUNTINGTON NATIONAL BANK', 2);
insert into "Garden" (id, name, "userId") values (42, 'DEUTSCHE BANK S.P.A.', 2);
insert into "Garden" (id, name, "userId") values (43, 'CENTENNIAL BANK', 2);
insert into "Garden" (id, name, "userId") values (44, 'Raiffeisenbank Bidingen eG', 2);
insert into "Garden" (id, name, "userId") values (45, 'FIRST STATE BANK', 2);
insert into "Garden" (id, name, "userId") values (46, 'Caisse des dépôts et consignations - section générale', 2);
insert into "Garden" (id, name, "userId") values (47, 'Bank Spółdzielczy w Zwoleniu', 2);
insert into "Garden" (id, name, "userId") values (48, 'BNP Paribas', 2);
insert into "Garden" (id, name, "userId") values (49, 'De Lage Landen International B.V.', 2);
insert into "Garden" (id, name, "userId") values (50, 'GREAT WESTERN BANK', 2);
insert into "Garden" (id, name, "userId") values (51, 'FIRST STATE BANK', 2);
insert into "Garden" (id, name, "userId") values (52, 'Akciju sabiedrība "Citadele banka"', 2);
insert into "Garden" (id, name, "userId") values (53, 'Raiffeisenbank Saalbach-Hinterglemm-Viehhofen eGen', 2);
insert into "Garden" (id, name, "userId") values (54, 'BANCORP SOUTH', 2);
insert into "Garden" (id, name, "userId") values (55, 'FIRST NATIONAL BANK', 2);
insert into "Garden" (id, name, "userId") values (56, 'FIRST BANK', 2);
insert into "Garden" (id, name, "userId") values (57, 'WEBSTER BANK', 2);
insert into "Garden" (id, name, "userId") values (58, 'PROSPERITY BANK', 2);
insert into "Garden" (id, name, "userId") values (59, 'FIRST COMMUNITY BANK', 2);
insert into "Garden" (id, name, "userId") values (60, 'UNITED COMMUNITY BANK', 2);
insert into "Garden" (id, name, "userId") values (61, 'EASTERN BANK', 2);
insert into "Garden" (id, name, "userId") values (62, 'Coöperatieve Rabobank U.A.', 2);
insert into "Garden" (id, name, "userId") values (63, 'BYLINE BANK', 2);
insert into "Garden" (id, name, "userId") values (64, 'SOUTH STATE BANK', 2);
insert into "Garden" (id, name, "userId") values (65, 'BANCO BPM SOCIETA'' PER AZIONI', 2);
insert into "Garden" (id, name, "userId") values (66, 'BANCA SIMETICA S.P.A.', 2);
insert into "Garden" (id, name, "userId") values (67, 'Raiffeisenbank Unteres Zusamtal eG', 2);
insert into "Garden" (id, name, "userId") values (68, 'HERITAGE BANK', 2);
insert into "Garden" (id, name, "userId") values (69, 'US BANK', 2);
insert into "Garden" (id, name, "userId") values (70, 'THE PEOPLES BANK', 2);
insert into "Garden" (id, name, "userId") values (71, 'Raiffeisenbank Wüstenselbitz eG', 2);
insert into "Garden" (id, name, "userId") values (72, 'BMO HARRIS BANK', 2);
insert into "Garden" (id, name, "userId") values (73, 'Volksbank Weschnitztal eG', 2);
insert into "Garden" (id, name, "userId") values (74, 'BANK OF AMERICA', 2);
insert into "Garden" (id, name, "userId") values (75, 'CATHAY BANK', 2);
insert into "Garden" (id, name, "userId") values (76, 'Raiffeisenbank Region Parndorf eGen', 2);
insert into "Garden" (id, name, "userId") values (77, 'INTERBANK', 2);
insert into "Garden" (id, name, "userId") values (78, 'CITIZENS BUSINESS BANK', 2);
insert into "Garden" (id, name, "userId") values (79, 'FIRST TENNESSEE BANK', 2);
insert into "Garden" (id, name, "userId") values (80, 'Raiffeisen Regionalbank Achensee eGen', 2);
insert into "Garden" (id, name, "userId") values (81, 'BANCO BPM SOCIETA'' PER AZIONI', 2);
insert into "Garden" (id, name, "userId") values (82, 'CAIXABANK S.A.', 2);
insert into "Garden" (id, name, "userId") values (83, 'Banco Bilbao Vizcaya Argentaria, S.A.', 2);
insert into "Garden" (id, name, "userId") values (84, 'Erste Bank der oesterreichischen Sparkassen AG', 2);
insert into "Garden" (id, name, "userId") values (85, 'VR-Bank Coburg eG', 2);
insert into "Garden" (id, name, "userId") values (86, 'Kreissparkasse Melle', 2);
insert into "Garden" (id, name, "userId") values (87, 'FIRST CITIZENS BANK & TRUST COMPANY', 2);
insert into "Garden" (id, name, "userId") values (88, 'CATHAY BANK', 2);
insert into "Garden" (id, name, "userId") values (89, 'Bank Spółdzielczy Ziemi Łowickiej w Łowiczu', 2);
insert into "Garden" (id, name, "userId") values (90, 'Sparkasse Pöllau AG', 2);
insert into "Garden" (id, name, "userId") values (91, 'UNITED BANK', 2);
insert into "Garden" (id, name, "userId") values (92, 'BANCO BPM SOCIETA'' PER AZIONI', 2);
insert into "Garden" (id, name, "userId") values (93, 'VR Bank München Land eG', 2);
insert into "Garden" (id, name, "userId") values (94, 'PARK NATIONAL BANK', 2);
insert into "Garden" (id, name, "userId") values (95, 'PNC BANK', 2);
insert into "Garden" (id, name, "userId") values (96, 'Bank Millennium S.A.', 2);
insert into "Garden" (id, name, "userId") values (97, 'FIRST NATIONAL BANK OF PENNSYLVANIA', 2);
insert into "Garden" (id, name, "userId") values (98, 'SANTANDER BANK', 2);
insert into "Garden" (id, name, "userId") values (99, 'NBH BANK', 2);
insert into "Garden" (id, name, "userId") values (100, 'PNC BANK', 2);